[DUMMY]
bbox = "None" # [27.842360,39.637753,27.941923,39.677070]
address = 'Bucharest, Romania'
network_type = "all_private"  # {"all_private", "all", "bike", "drive", "drive_service", "walk"}
sample_count = 1000
minimum_distance = 50  # minimum footstep distance is X meters
maximum_distance = 120 #3 max... footstep
avg_speed = 1.4 # pedestrian
constant = "False" # means random
start_date = "2019-8-03 16:40:21"
end_date = "2021-12-03 15:40:21"
date_mixing = "True"  # Random date specified start_date, end_date
reload = "False"  # Downloads OSM data again if set True
crs = "epsg:3857"
recursive_sample = 200  # we will duplicate 20 rows of generated points for each step till repeated_times
repeated_times = 3  #

[DB]
host = "127.0.0.1"
username = "postgres"
password = "figo1190"
db = 'postgis_30_sample'
port = 5432
points_table_name = 'points'
lines_table_name = 'lines'
if_exists='append'  # fail, append

[GEOSERVER]
[LIVE]
host="http://84.239.34.36:8080/geoserver"
username = "admin"
password = "Geopass"
[TEST]
host="http://127.0.0.1:8080/geoserver"
username = "admin"
password = "Geopass"